[build]
  publish = "netlify"
  functions = "netlify/functions"

[[redirects]]
  from = "/netlify/data/cocktail_data_backup.json"
  to = "/netlify/data/cocktail_data_backup.json"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/cocktails/*"
  to = "/cocktails/index.html"
  status = 200

[[redirects]]
  from = "/cocktail.html"
  to = "/cocktail.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200