[build]
  publish = "envs/old-blue-last"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/cocktails/*"
  to = "/cocktails/index.html"
  status = 200

[[redirects]]
  from = "/cocktail.html"
  to = "/cocktail.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200