name: Deploy Environments

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'envs/**'
      - 'core-components/**'
      - 'patches/**'
      - 'scripts/**'
      - '.github/workflows/deploy.yml'
      - 'trigger-ci.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        venue: [old-blue-last, adam-and-eve]

    steps:
      - name: Debug GitHub workspace
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Run patch engine
        run: |
          echo "[CI] Running patch for ${{ matrix.venue }}"
          python3 patches/apply_patch.py "${{ matrix.venue }}" || echo "(no patch needed)"

      - name: Save patch log
        run: |
          mkdir -p scripts/logs/
          echo '{"venue": "${{ matrix.venue }}", "commit": "${{ github.sha }}", "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"}' > scripts/logs/${{ matrix.venue }}.json

      - name: Deploy to Netlify
        working-directory: envs/${{ matrix.venue }}
        run: |
          echo "Deploying ${{ matrix.venue }} to Netlify..."
          netlify deploy --prod --dir=. --site="${{ secrets[format('NETLIFY_SITE_ID_{0}', matrix.venue | upper)] }}"
