[build]
  publish = "envs/old-blue-last"
  functions = "envs/old-blue-last/netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/cocktails/*"
  to = "/cocktails/index.html"
  status = 200

[[redirects]]
  from = "/cocktail.html"
  to = "/cocktail.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200