on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'envs/**'
      - 'core-components/**'
      - 'patches/**'
      - '.github/workflows/deploy.yml'
      - 'trigger-ci.txt'
