\- name: List changed files (safe)
  run: |
    echo "These files changed:"
    git rev-parse --is-inside-work-tree || exit 0
    git fetch --no-tags --prune --depth=10 origin main
    git diff --name-only HEAD^ HEAD || echo "No diff available"name: Deploy Environments

on:
  push:
    branches:
      - main
    paths:
      - 'envs/**'
      - 'core-components/**'
      - 'patches/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: List changed files (safe)
        run: |
          echo "These files changed:"
         git rev-parse --is-inside-work-tree || exit 0
   	 git fetch --no-tags --prune --depth=10 origin main
   	 git diff --name-only HEAD^ HEAD || echo "No diff available"

      - name: (Optional) Run patch engine
        run: |
          echo "Patching environments if required..."
          python3 patches/apply_patch.py || echo "Patch skipped (optional or already patched)"

      - name: Deploy logic placeholder
        run: |
          echo "Deploy stage here"
